### PR TITLE
Using TelegramClient Monad (#30)

### PR DESCRIPTION
**Pull request by kemphack**
This change is [Reviewable](https://reviewable.io/reviews/mcl1303/taskbot/50)

### CODE REVIEW

**Comment by cblp** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[stack.yaml, line 1 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsEpTIb89Sd6CMdHl5:-KgsEpTIb89Sd6CMdHl6:bjy1eu2) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/stack.yaml#L1)):*
> ```YAML
> resolver: lts-8.6
> ```

Это лучше делать отдельным патчем. Но ок, пусть остаётся здесь.

---

*[app/BotCommands.hs, line 22 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsFAmJhGZ8Ob0vOVY8:-KgsFAmKd_8UpRkn_LTM:bgbdemb) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/BotCommands.hs#L22)):*
> ```Haskell
> sendMessageB :: Int -> Text -> TelegramClient ()
> sendMessageB chatId mesText = do
>     _ <- sendMessageM (sendMessageRequest (ChatId $ fromIntegral chatId) mesText)
> ```

эх, строка на 1 сивол вылезает за допустимую границу

можно поставить ($) после _sendMessageM_

можно использовать _Control.Monad.void_ вместо `_ <-`

это всё строчку не сократит, но позволит красиво перенести

кстати, разве здесь нужен _fromIntegral_?

---

*[app/DB.hs, line 38 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsGNK17y0bqi5ucodC:-KgsGNK17y0bqi5ucodD:b923i9h) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/DB.hs#L38)):*
> ```Haskell
> dbfile = "./db.sqlite"
> 
> runDBM
> ```

Почему _M_?

---

*[app/Main.hs, line 49 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHGFpKXtO1idzr5OH:-KgsHGFqXT7nDXvi95ly:b-6lf7p7) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L49)):*
> ```Haskell
>     -> TelegramClient ()
> bot curOffset = do
>     uResult <- getUpdatesM uRequest
> ```

во фразе "updates request" главное слово — "updates". назови переменную _updatesReq_

---

*[app/Main.hs, line 50 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsGigDY6mF0dQBpHqC:-KgsGigDY6mF0dQBpHqD:b7gdl3v) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L50)):*
> ```Haskell
> bot curOffset = do
>     uResult <- getUpdatesM uRequest
>     let Response{result} = uResult
> ```

Response{result} <- getUpdatesM uRequest

---

*[app/Main.hs, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHJKCwrv5ejcEVvEX:-KgsHJKCwrv5ejcEVvEY:bxr6j7k) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L58)):*
> ```Haskell
>         Nothing -> bot curOffset
>   where
>     uRequest = GetUpdatesRequest curOffset Nothing Nothing Nothing
> ```

getUpdatesRequest{updates_offset = curOffset}

---

*[app/Main.hs, line 68 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHdKNK9fUYWtpwvWh:-KgsHdKOuwqmnHYKO47U:b-2yc8cn) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L68)):*
> ```Haskell
>         (bot offset)
>         token
>         manager
> ```

И на одной строчке помещается.

---

*[app/Tools.hs, line 39 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHmKce5ay9Zaup5Vq:-KgsHmKce5ay9Zaup5Vr:b923i9h) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Tools.hs#L39)):*
> ```Haskell
> putLog = hPutStrLn stderr
> 
> putLogM :: String
> ```

Почему _M_?

---

*[app/Tools.hs, line 66 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHtTJC4MEh65ZckUf:-KgsHtTJC4MEh65ZckUg:b923i9h) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Tools.hs#L66)):*
> ```Haskell
>     readWritableFile = openFile fileName ReadWriteMode >>= hGetContents
> 
> saveOffsetM :: FilePath -> Int -> TelegramClient ()
> ```

Почему _M_?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/Main.hs, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHJKCwrv5ejcEVvEX:-Khi1UkXWhpPcH86O-xC:bsuhji8) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L58)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

getUpdatesRequest{updates_offset = curOffset}
</blockquote></details>

• Fields of ‘GetUpdatesRequest’ not initialised: updates_limit,
                                                     updates_timeout, updates_allowed_updates
    • In the expression: GetUpdatesRequest {updates_offset = curOffset}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[app/BotCommands.hs, line 22 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KhknUgV8sA9pUqEjVfu:-KhknUgV8sA9pUqEjVfv:b-wz26ao) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/BotCommands.hs#L22)):*
> ```Haskell
> sendMessageB :: Int -> Text -> TelegramClient ()
> sendMessageB chatId mesText = do
>     _ <- sendMessageM messageRequest
> ```

можно использовать _Control.Monad.void_ вместо `_ <-`

---

*[app/BotCommands.hs, line 25 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khknh5-7iHepp-qofgP:-Khknh5-7iHepp-qofgQ:b-cm3osr) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/BotCommands.hs#L25)):*
> ```Haskell
>     pure ()
>   where
>     messageRequest = sendMessageRequest (ChatId $ fromIntegral chatId) mesText
> ```

разве здесь нужен _fromIntegral_?

---

*[app/Main.hs, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHJKCwrv5ejcEVvEX:-KhkoEBQrjoDeDD3Izd4:bltv67u) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L58)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

• Fields of ‘GetUpdatesRequest’ not initialised: updates_limit,
                                                     updates_timeout, updates_allowed_updates
    • In the expression: GetUpdatesRequest {updates_offset = curOffset}
</blockquote></details>

да-да, именно поэтому

---

*[app/Tools.hs, line 39 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khko2pjCTWUh9Tq8Ubh:-Khko2pjCTWUh9Tq8Ubi:b923ngc) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/Tools.hs#L39)):*
> ```Haskell
> putLog = hPutStrLn stderr
> 
> putLogTM :: String
> ```

Почему _T_?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/Main.hs, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHJKCwrv5ejcEVvEX:-Ki6cT8a5NSOEFTXfkOo:b-8zej2r) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L58)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

да-да, именно поэтому
</blockquote></details>

Так они должны быть инициализированы - заполнены Nothing. А этот способ на этапе компиляции не проходит.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/Tools.hs, line 39 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khko2pjCTWUh9Tq8Ubh:-Ki6cczzZoujr7CRyyjr:b-eggxg7) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/Tools.hs#L39)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Почему _T_?
</blockquote></details>

TelegramMonad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[app/Main.hs, line 58 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHJKCwrv5ejcEVvEX:-Ki9_aAiotoENuDhRYys:b6jv25f) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Main.hs#L58)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

Так они должны быть инициализированы - заполнены Nothing. А этот способ на этапе компиляции не проходит.
</blockquote></details>

почему у меня компилируется?

```haskell
λ> getUpdatesRequest{updates_offset = Just 42}
GetUpdatesRequest {updates_offset = Just 42, updates_limit = Nothing, updates_timeout = Nothing, updates_allowed_updates = Nothing}
```

---

*[app/Tools.hs, line 39 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khko2pjCTWUh9Tq8Ubh:-Ki9avmMKjrZSZ5RRbIu:bcp9xba) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/Tools.hs#L39)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

TelegramMonad
</blockquote></details>

_TelegramClient_ же

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/DB.hs, line 38 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsGNK17y0bqi5ucodC:-KiBP5cBER_dDvnH8jUy:b-c3gpdd) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/DB.hs#L38)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Почему _M_?
</blockquote></details>

Разве это проблема не разрешилась?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/BotCommands.hs, line 25 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khknh5-7iHepp-qofgP:-KiBPWStrAqh3IBbYK8U:b4ofoff) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/BotCommands.hs#L25)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

разве здесь нужен _fromIntegral_?
</blockquote></details>

• Couldn't match expected type ‘Integer’ with actual type ‘Int’
    • In the first argument of ‘ChatId’, namely ‘chatId’

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/Tools.hs, line 39 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khko2pjCTWUh9Tq8Ubh:-KiBQFqCETLEHmHVcm3_:bqhcfck) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/Tools.hs#L39)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

_TelegramClient_ же
</blockquote></details>

Лучше TM, а не TC или TCM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/Tools.hs, line 39 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHmKce5ay9Zaup5Vq:-KiBQQxdHvAAoxnAbN74:b-ja0rvn) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Tools.hs#L39)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Почему _M_?
</blockquote></details>

Разве эта проблема не разрешилась?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/Tools.hs, line 66 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHtTJC4MEh65ZckUf:-KiBQV6aPI2UjiXIg5BS:b-ja0rvn) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Tools.hs#L66)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Почему _M_?
</blockquote></details>

Разве эта проблема не разрешилась?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[app/BotCommands.hs, line 25 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khknh5-7iHepp-qofgP:-KiEog5tHp3dl0iT2sa_:b-dm5yhj) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/BotCommands.hs#L25)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

• Couldn't match expected type ‘Integer’ with actual type ‘Int’
    • In the first argument of ‘ChatId’, namely ‘chatId’

</blockquote></details>

Понятно. Лучше вместо этого сделай аргумент этой функции _Integer_.

---

*[app/Tools.hs, line 39 at r1](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KgsHmKce5ay9Zaup5Vq:-KiEpG8cREqd6xvxioV1:b-sf4wam) ([raw file](https://github.com/mcl1303/taskbot/blob/b45773268fe43263fc1836ea9f433384c41ee3e8/app/Tools.hs#L39)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

Разве эта проблема не разрешилась?
</blockquote></details>

ещё нет

---

*[app/Tools.hs, line 39 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khko2pjCTWUh9Tq8Ubh:-KiEp23vcFo39gybFspS:b9lf5wf) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/Tools.hs#L39)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

Лучше TM, а не TC или TCM
</blockquote></details>

Эта функция не отличается от _putLog_ монадностью. Они отличаются только телеграмностью. Достаточно _T_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by kemphack** [comment]
*[app/BotCommands.hs, line 25 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khknh5-7iHepp-qofgP:-KjERLkf3DA5kK4A2jaN:b-rhu9xw) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/BotCommands.hs#L25)):*
<details><summary><i>Previously, cblp (Yuriy Syrovetskiy) wrote…</i></summary><blockquote>

Понятно. Лучше вместо этого сделай аргумент этой функции _Integer_.
</blockquote></details>

Эта функция в телеграмАпи

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/BotCommands.hs, line 25 at r2](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-Khknh5-7iHepp-qofgP:-KjHdbl3EOEZMGVtNC3O:bn5v7i9) ([raw file](https://github.com/mcl1303/taskbot/blob/2abf182d93083fb0224287355a4b75d6053d21ce/app/BotCommands.hs#L25)):*
<details><summary><i>Previously, kemphack wrote…</i></summary><blockquote>

Эта функция в телеграмАпи
</blockquote></details>

Да, там требуется _Int64_. Тогда твоя _sendMessageB_ тоже должна принимать _Int64_.

---

*[app/BotCommands.hs, line 24 at r3](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KjHcN8pFXO9lzbfzwSx:-KjHcN8q84vvy9L2aOgX:b-thfj9e) ([raw file](https://github.com/mcl1303/taskbot/blob/8f680687fb6bec005225cf94171d5dbe459621a2/app/BotCommands.hs#L24)):*
> ```Haskell
> sendMessageB chatId mesText = do
>     void $ sendMessageM messageRequest
>     pure ()
> ```

Лишняя строка

---

*[app/BotCommands.hs, line 43 at r3](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KjHeQtzvZGmwxNUb098:-KjHeQu-x-bcralNnyQF:b8n85dx) ([raw file](https://github.com/mcl1303/taskbot/blob/8f680687fb6bec005225cf94171d5dbe459621a2/app/BotCommands.hs#L43)):*
> ```Haskell
> 
> addNote :: Int -- ^ UserId - who wants to insert
>         -> Text -- ^ Inserting note
> ```

"Inserting note" — это "вставляющая заметка", а не "вставляемая". Лучше написать "Note to insert", "Note to add" или просто "Note".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/BotCommands.hs, line 35 at r5](https://reviewable.io:443/reviews/mcl1303/taskbot/50#-KjOwPwmTYKk5Mly6zTE:-KjOwPwmTYKk5Mly6zTF:blutigf) ([raw file](https://github.com/mcl1303/taskbot/blob/1adcced87bd5fcd166a108cf502b8fbc8198389c/app/BotCommands.hs#L35)):*
> ```Haskell
>         Nothing ->
>             void . sendMessageM $
>                 sendMessageRequest (ChatId chatId) (pack "Записей нет.")
> ```

лишний _pack_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mcl1303/taskbot/50)*

**Comment by cblp** [comment]
Merged

**Pull request closed without merging**
